#!/bin/sh

coffee -r ./app/scripts/production-replacements.coffee -c -o public/javascripts app/scripts/copypasta.coffee
git update-index --no-assume-unchanged public/javascripts/copypasta.js
git add -f public/javascripts/copypasta.js
